#!/bin/bash

# Function to print workspaces and loop through them
print_calendar() {
    # Get the number of workspaces in Xfce
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"

    # Open widgets
    if [ ! -f "$LOCK_FILE" ]; then
        /usr/local/bin/eww -c ~/.config/eww open calendar
        sleep 0.5
        touch $LOCK_FILE
    else
        eww close calendar
        rm "$LOCK_FILE"
        exit
    fi
}

print_calendar
